int changedir(char* arr,char* sym,int k,char* cdpwd,char* sy);
void pwd();
int echo(char *arr[100],int k);
void history(char *path);
void history_num(char *arr,char* path);
int repeat(char* arr[],int k);
void ls(char *dir,char *arr[],int k);
void lsa(char *arr);
//void lsl(char* arr,int k);
void lsla(char* arr,int x);
void processes(char *arr[],int k);
void pinfo(char *arr[],int k);
extern int alphasort();
void file(char *arr[], int k,char* sy);
void redirection(char *arr[], int k, int o,char* sym);
void jobs(char *a[],int n);
void sigjobs(char *ar[],int n);
void display(char *sim);
void bg(char *ar[]);
void fg(char *ar[]);
void delprocess(int id);
void background(char *arr[],int n);
void foreground(char *arr[], int k);
void overkill();